Repository apache/dolphinscheduler-website, pull requests merged in 2021-12, with the labels that each got.

#576 Remove plugin sidebar and add datasource
  site_config/development.js
Labels: bug

#580 Add asf config to strict behavior
  .asf.yaml
Labels: enhancement

#587 Recover website deploy configuration
  .asf.yaml
Labels: bug

#581 [Feature-7419][Website][docs][doc-zh]Add unsubscribe method to website
  community/en-us/development/subscribe.md
  community/zh-cn/development/subscribe.md
Labels: First-time contributor

#591 Revert "[Fix] Update youzan. (#586)"
  .github/workflows/dead-link-checker.yaml
Labels: enhancement, waiting for review

#592 Upgrade 2.0.1 "upgrade" doc and rm duplicate config in pseudo-cluster
  docs/en-us/2.0.1/user_doc/guide/installation/pseudo-cluster.md
  docs/en-us/2.0.1/user_doc/upgrade.md
  docs/zh-cn/2.0.1/user_doc/upgrade.md
Labels: bug, waiting for review

#590 add cache doc
  docs/en-us/dev/user_doc/architecture/cache.md
  docs/zh-cn/dev/user_doc/architecture/cache.md
  img/cache-evict.png
  site_config/docsdev.js
Labels: enhancement

#593 [Feature] Add logo.
  img/ourusers/yiyunxinxi.png
  img/ourusers/zhihuiqice.png
  site_config/home.jsx
Labels: enhancement

#610 update failover logic
  docs/en-us/dev/user_doc/architecture/design.md
  docs/zh-cn/dev/user_doc/architecture/design.md
  img/failover-master.jpg
  img/failover-worker.jpg
Labels: waiting user response

#594 [Feature-7465][Alert] Modifiy alert docs
  docs/en-us/dev/user_doc/guide/alert/enterprise-wechat.md
  docs/en-us/dev/user_doc/guide/parameter/built-in.md
  docs/zh-cn/dev/user_doc/guide/alert/enterprise-wechat.md
  docs/zh-cn/dev/user_doc/guide/parameter/built-in.md
  img/alert/enterprise-wechat-plugin.png
Labels: First-time contributor

#611 Move skywalking-agent to observability(1.3.9-2.0.2)
  docs/en-us/1.3.9/user_doc/skywalking-agent-deployment.md
  docs/en-us/2.0.0/user_doc/guide/observability/skywalking-agent.md
  docs/en-us/2.0.1/user_doc/guide/observability/skywalking-agent.md
  docs/zh-cn/1.3.9/user_doc/skywalking-agent-deployment.md
  docs/zh-cn/2.0.0/user_doc/guide/observability/skywalking-agent.md
  docs/zh-cn/2.0.1/user_doc/guide/observability/skywalking-agent.md
  site_config/docs1-3-9.js
  site_config/docs2-0-0.js
  site_config/docs2-0-1.js
Labels: enhancement, waiting for review

#609 [Bug-7389][docs-zh][docs] Fix System User Manual link failure in version 2.0.1 and version 2.0.0
  docs/en-us/2.0.0/user_doc/architecture/design.md
  docs/en-us/2.0.0/user_doc/guide/system-manual.md
  docs/en-us/2.0.1/user_doc/architecture/design.md
  docs/en-us/dev/user_doc/architecture/design.md
  docs/zh-cn/2.0.0/user_doc/architecture/design.md
  docs/zh-cn/2.0.0/user_doc/guide/system-manual.md
  docs/zh-cn/2.0.1/user_doc/architecture/design.md
  docs/zh-cn/dev/user_doc/architecture/design.md
Labels: bug
