Repository apache/dolphinscheduler-website, pull requests merged in 2022-11, with the labels that each got.

#840 [feat] Only check all docs dead link in schedule event
  .github/workflows/dead-link-checker.yaml
Labels: community

#839 [feat] Change python API into other repo
  .github/workflows/website.yml
  scripts/conf.sh
  scripts/prepare_docs.sh
Labels: develop

#842 [3.0.2-release] Update docs for 3.0.2 release
  download/en-us/download.md
  download/zh-cn/download.md
  scripts/conf.sh
Labels: release
