Repository apache/dolphinscheduler-website, pull requests merged in 2022-04, with the labels that each got.

#713 [Feature-8023][Document] Add example and notice about task type Python
  docs/en-us/2.0.5/user_doc/guide/task/python.md
  docs/en-us/dev/user_doc/guide/task/python.md
  docs/zh-cn/2.0.5/user_doc/guide/task/python.md
  docs/zh-cn/dev/user_doc/guide/task/python.md
  img/tasks/demo/python.jpg
  img/tasks/demo/python_custom_param.jpg
  img/tasks/demo/python_custom_param_ui_next.jpg
  img/tasks/demo/python_ui_next.jpg
  img/tasks/icons/python.png
Labels: don't merge, task

#757 [ci] Add CI failed when any change in docs
  .asf.yaml
  .github/workflows/change-docs.yaml
Labels: CI/CD, history-docs-change

#760 [ci] Add schedule deploy and revert prohibit docs change
  .github/workflows/change-docs.yaml
  .github/workflows/website.yml
Labels: CI/CD

#762 [Feature]Added banner Prompt
  src/components/header/index.jsx
  src/components/header/index.scss
Labels: enhancement

#766 Correct parameter set syntax
  .gitignore
  docs/2.0.0/docs/en/guide/parameter/context.md
  docs/2.0.1/docs/en/guide/parameter/context.md
  docs/2.0.2/docs/en/guide/parameter/context.md
  docs/2.0.3/docs/en/guide/parameter/context.md
  docs/2.0.5/docs/en/guide/parameter/context.md
Labels: bug, history-docs-change

#767 [ci] Add branch history-docs as protect branch
  .asf.yaml
Labels: CI/CD

#764 Add some missing change files
  img/alert/agentid.png
  img/alert/corpid.png
  img/alert/secret.png
  img/alert/userid.png
  src/pages/docs/index.md.jsx
Labels: bug

#763 Update prepare script in readme
  HOW_PREPARE_WOKR.md
  README.md
Labels: enhancement, develop

#768 update compile command
  development/en-us/development-environment-setup.md
  development/zh-cn/development-environment-setup.md
Labels: waiting for review

#769 [chore] Migrate development docs into main repo
  .gitignore
  community/en-us/join/review.md
  community/zh-cn/join/review.md
  development/en-us/api-standard.md
  development/en-us/architecture-design.md
  development/en-us/backend/mechanism/global-parameter.md
  development/en-us/backend/mechanism/overview.md
  development/en-us/backend/mechanism/task/switch.md
  development/en-us/backend/spi/alert.md
  development/en-us/backend/spi/datasource.md
  development/en-us/backend/spi/registry.md
  development/en-us/backend/spi/task.md
  development/en-us/development-environment-setup.md
  development/en-us/e2e-test.md
  development/en-us/frontend-development.md
  development/en-us/have-questions.md
  development/zh-cn/api-standard.md
  development/zh-cn/architecture-design.md
  development/zh-cn/backend/mechanism/global-parameter.md
  development/zh-cn/backend/mechanism/overview.md
  development/zh-cn/backend/mechanism/task/switch.md
  development/zh-cn/backend/spi/alert.md
  development/zh-cn/backend/spi/datasource.md
  development/zh-cn/backend/spi/registry.md
  development/zh-cn/backend/spi/task.md
  development/zh-cn/development-environment-setup.md
  development/zh-cn/e2e-test.md
  development/zh-cn/frontend-development.md
  development/zh-cn/have-questions.md
  img/architecture-design/dag_examples_ch_zn.png
  img/architecture-design/dag_examples_en_us.png
  img/architecture-design/distributed_lock_ch_zn.png
  img/architecture-design/distributed_lock_en_us.png
  img/architecture-design/distributed_lock_procss_ch_zn.png
  img/architecture-design/distributed_lock_procss_en_us.png
  img/architecture-design/fault-tolerant_ch_zn.png
  img/architecture-design/fault-tolerant_en_us.png
  img/architecture-design/fault-tolerant_master_ch_zn.png
  img/architecture-design/fault-tolerant_master_en_us.png
  img/architecture-design/fault-tolerant_worker_ch_zn.png
  img/architecture-design/fault-tolerant_worker_en_us.png
  img/architecture-design/grpc_en_us.png
  img/architecture-design/lack_thread_ch_zn.png
  img/architecture-design/lack_thread_en_us.png
  img/architecture-design/process_priority_en_us.png
  img/architecture-design/task_priority_en_us.png
  img/architecture-en.jpg
  img/architecture.jpg
  scripts/prepare_docs.sh
Labels: develop

#770 add news
  blog/en-us/Apache_DolphinScheduler_s_Graduation_From_ASF_Incubator.md
  blog/zh-cn/Apache_DolphinScheduler_s_Graduation_From_ASF_Incubator.md
  img/2022-4-14/1.png
  img/2022-4-14/2.png
  img/2022-4-14/3.png
  site_config/blog.js
  site_config/home.jsx
Labels: blog

#775 Support fetch released docs from main repo
  .github/workflows/change-docs.yaml
  HOW_PREPARE_WOKR.md
  scripts/conf.sh
  scripts/prepare_docs.sh
  scripts/rsync_content.sh
Labels: develop, CI/CD

#778 [release] Change release docs
  blog/en-us/Apache-DolphinScheduler-2.0.1.md
  blog/zh-cn/Apache-DolphinScheduler-2.0.1.md
  community/en-us/release-post.md
  community/en-us/release-prepare.md
  community/en-us/release.md
  community/zh-cn/release-post.md
  community/zh-cn/release-prepare.md
  community/zh-cn/release.md
  download/en-us/download.md
  download/zh-cn/download.md
  site_config/home.jsx
  sitemap.xml
Labels: community

#782 [Bug]fix Chinese Official website link error link
  site_config/home.jsx
Labels: bug

#781 [ci] prepare_doc compatible version below bash 4
  README.md
  scripts/conf.sh
  scripts/rsync_content.sh
Labels: CI/CD
