Repository apache/dolphinscheduler-website, pull requests merged in 2022-03, with the labels that each got.

#709 Add missing sidebar for alert plugin in dev doc
  site_config/docsdev.js
Labels: bug, plugin

#707 Add new steps in release-post include history-version and pypi release
  community/en-us/release-post.md
  community/zh-cn/release-post.md
Labels: enhancement, community

#710 [Docs] Add re-upload to resource center
  docs/en-us/dev/user_doc/guide/resource.md
  docs/zh-cn/dev/user_doc/guide/resource.md
  img/reupload_file_en.png
Labels: enhancement, First-time contributor

#704 adding new Branch git command
  community/en-us/development/submit-code.md
  community/zh-cn/development/submit-code.md
Labels: waiting for review, community

#716 [community] Remove change download page in release.md
  community/en-us/release.md
  community/zh-cn/release.md
Labels: community

#723 [Feature-8026][Document] Add example and notice about task type DataX
  docs/en-us/dev/user_doc/guide/task/datax.md
  docs/zh-cn/dev/user_doc/guide/task/datax.md
  img/tasks/demo/datax_task01.png
  img/tasks/demo/datax_task02.png
  img/tasks/demo/datax_task03.png
  img/tasks/icons/datax.png
Labels: refactor, task

#721 Proofreading dev documents under /user_doc/guide/project
  docs/en-us/dev/user_doc/guide/project/project-list.md
  docs/en-us/dev/user_doc/guide/project/task-instance.md
  docs/en-us/dev/user_doc/guide/project/workflow-definition.md
  docs/en-us/dev/user_doc/guide/project/workflow-instance.md
  docs/zh-cn/dev/user_doc/guide/project/workflow-definition.md
Labels: Proofreading

#726 [ci] Only run website deploy when push to master branch
  .dlc.json
  .github/workflows/website.yml
Labels: CI/CD

#728 add news
  blog/en-us/Exploration_and_practice_of_Tujia_Big_Data_Platform_Based.md
  blog/zh-cn/Exploration_and_practice_of_Tujia_Big_Data_Platform_Based.md
  img/2022-3-9/1.jpeg
  img/2022-3-9/10.png
  img/2022-3-9/2.png
  img/2022-3-9/3.png
  img/2022-3-9/4.png
  img/2022-3-9/5.png
  img/2022-3-9/6.png
  img/2022-3-9/7.png
  img/2022-3-9/8.png
  img/2022-3-9/9.png
  img/2022-3-9/Eng/1.jpeg
  img/2022-3-9/Eng/2.png
  img/2022-3-9/Eng/3.png
  img/2022-3-9/Eng/4.png
  img/2022-3-9/Eng/5.png
  img/2022-3-9/Eng/6.png
  img/2022-3-9/Eng/7.png
  img/2022-3-9/Eng/8.png
  img/2022-3-9/Eng/9.png
  site_config/blog.js
  site_config/home.jsx
Labels: blog

#727 [community] Add send E-mail to apache announce after release process
  community/en-us/release.md
  community/zh-cn/release.md
Labels: community

#732 Proofreading dev documents under /user_doc/guide/task
  docs/en-us/dev/user_doc/guide/task/conditions.md
  docs/en-us/dev/user_doc/guide/task/datax.md
  docs/en-us/dev/user_doc/guide/task/dependent.md
  docs/en-us/dev/user_doc/guide/task/emr.md
  docs/en-us/dev/user_doc/guide/task/flink.md
  docs/en-us/dev/user_doc/guide/task/http.md
  docs/en-us/dev/user_doc/guide/task/map-reduce.md
  docs/en-us/dev/user_doc/guide/task/pigeon.md
  docs/en-us/dev/user_doc/guide/task/python.md
  docs/en-us/dev/user_doc/guide/task/shell.md
  docs/en-us/dev/user_doc/guide/task/spark.md
  docs/en-us/dev/user_doc/guide/task/sql.md
  docs/en-us/dev/user_doc/guide/task/stored-procedure.md
  docs/en-us/dev/user_doc/guide/task/sub-process.md
  docs/en-us/dev/user_doc/guide/task/switch.md
  docs/zh-cn/dev/user_doc/guide/task/datax.md
  docs/zh-cn/dev/user_doc/guide/task/flink.md
  docs/zh-cn/dev/user_doc/guide/task/pigeon.md
  docs/zh-cn/dev/user_doc/guide/task/spark.md
  docs/zh-cn/dev/user_doc/guide/task/sql.md
  docs/zh-cn/dev/user_doc/guide/task/switch.md
Labels: waiting for review, Proofreading

#738 Proofreading dev documents under /user_doc/guide
  docs/en-us/dev/user_doc/guide/expansion-reduction.md
  docs/en-us/dev/user_doc/guide/flink-call.md
  docs/en-us/dev/user_doc/guide/introduction.md
  docs/en-us/dev/user_doc/guide/monitor.md
  docs/en-us/dev/user_doc/guide/open-api.md
  docs/en-us/dev/user_doc/guide/quick-start.md
  docs/en-us/dev/user_doc/guide/resource.md
  docs/en-us/dev/user_doc/guide/security.md
  docs/en-us/dev/user_doc/guide/upgrade.md
  docs/zh-cn/dev/user_doc/guide/introduction.md
  img/video_cover/quick-use.png
Labels: enhancement, Proofreading

#735 Proofreading dev documents under /user_doc/guide/installation
  docs/en-us/dev/user_doc/guide/installation/cluster.md
  docs/en-us/dev/user_doc/guide/installation/docker.md
  docs/en-us/dev/user_doc/guide/installation/hardware.md
  docs/en-us/dev/user_doc/guide/installation/kubernetes.md
  docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
  docs/en-us/dev/user_doc/guide/installation/skywalking-agent.md
  docs/en-us/dev/user_doc/guide/installation/standalone.md
Labels: waiting user response, Proofreading

#740 fix all the 'as follow' grammar
  docs/en-us/dev/user_doc/architecture/configuration.md
  docs/en-us/dev/user_doc/architecture/design.md
  docs/en-us/dev/user_doc/architecture/task-structure.md
  docs/en-us/dev/user_doc/guide/alert/dingtalk.md
  docs/en-us/dev/user_doc/guide/alert/enterprise-webexteams.md
  docs/en-us/dev/user_doc/guide/alert/enterprise-wechat.md
  docs/en-us/dev/user_doc/guide/alert/telegram.md
  docs/en-us/dev/user_doc/guide/installation/docker.md
  docs/en-us/dev/user_doc/guide/installation/hardware.md
  docs/en-us/dev/user_doc/guide/installation/kubernetes.md
  docs/en-us/dev/user_doc/guide/installation/pseudo-cluster.md
  docs/en-us/dev/user_doc/guide/installation/standalone.md
  docs/en-us/dev/user_doc/guide/parameter/context.md
  docs/en-us/dev/user_doc/guide/parameter/priority.md
  docs/en-us/dev/user_doc/guide/project/workflow-definition.md
  docs/en-us/dev/user_doc/guide/task/datax.md
  docs/en-us/dev/user_doc/guide/task/flink.md
  docs/en-us/dev/user_doc/guide/task/map-reduce.md
  docs/en-us/dev/user_doc/guide/task/spark.md
  docs/en-us/dev/user_doc/guide/task/sql.md
  docs/en-us/dev/user_doc/guide/task/switch.md
Labels: Proofreading

#741 [Feature-8025][Document] Add example and notice about task type HTTP
  docs/en-us/dev/user_doc/guide/task/datax.md
  docs/en-us/dev/user_doc/guide/task/flink.md
  docs/en-us/dev/user_doc/guide/task/http.md
  docs/en-us/dev/user_doc/guide/task/map-reduce.md
  docs/en-us/dev/user_doc/guide/task/shell.md
  docs/en-us/dev/user_doc/guide/task/spark.md
  docs/en-us/dev/user_doc/guide/task/sql.md
  docs/zh-cn/dev/user_doc/guide/task/http.md
  img/tasks/demo/http_task01.png
  img/tasks/icons/http.png
Labels: task

#742 Change structure of the dev directory
  docs/en-us/dev/user_doc/about/glossary.md
  docs/en-us/dev/user_doc/about/hardware.md
  docs/en-us/dev/user_doc/about/introduction.md
  docs/en-us/dev/user_doc/architecture/design.md
  docs/en-us/dev/user_doc/guide/installation/docker.md
  docs/en-us/dev/user_doc/guide/installation/kubernetes.md
  docs/en-us/dev/user_doc/guide/introduction.md
  docs/en-us/dev/user_doc/guide/start/quick-start.md
  docs/en-us/release/history-versions.md
  docs/zh-cn/dev/user_doc/about/glossary.md
  docs/zh-cn/dev/user_doc/about/hardware.md
  docs/zh-cn/dev/user_doc/about/introduction.md
  docs/zh-cn/dev/user_doc/architecture/design.md
  docs/zh-cn/dev/user_doc/guide/installation/kubernetes.md
  docs/zh-cn/dev/user_doc/guide/introduction.md
  docs/zh-cn/dev/user_doc/guide/start/docker.md
  docs/zh-cn/dev/user_doc/guide/start/quick-start.md
  docs/zh-cn/release/history-versions.md
  site_config/docsdev.js
Labels: refactor, format

#750 [Fix] [Website-9173]declare JSON body feature to the telegram.md
  docs/en-us/dev/user_doc/guide/alert/telegram.md
  docs/zh-cn/dev/user_doc/guide/alert/telegram.md
Labels: enhancement
